project_id = "ixkknbhlbafeucgmafpk"

[functions.generate-report]
verify_jwt = false

[functions.generate-ai-reply]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.generate-risk-mitigation]
verify_jwt = false

[functions.suggest-tasks]
verify_jwt = false
