parameters:
  nodeVersion: '20.x'

jobs:
- job: Build
  displayName: Build Web App
  pool:
    vmImage: ubuntu-latest
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: ${{ parameters.nodeVersion }}

    - script: npm ci
      displayName: Install dependencies

    - script: npm run build
      displayName: Build app

    - publish: dist
      artifact: webapp
      displayName: Publish web artifact
